# Generated by Django 4.1.7 on 2023-04-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecontent',
            old_name='photo',
            new_name='myphoto',
        ),
    ]
