# Generated by Django 4.1.7 on 2023-04-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0006_certification_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_title', models.CharField(max_length=255)),
                ('Project_description', models.TextField()),
                ('completion_date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='project_images')),
            ],
        ),
    ]
