# Generated by Django 4.1.7 on 2023-04-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0007_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Project_description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='thumbnail',
            new_name='project_images',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project_title',
            new_name='project_title',
        ),
    ]
