# Generated by Django 4.1.7 on 2023-04-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0009_project_custom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
